/**
 * Known Project Profiles
 *
 * Static data for major crypto assets.
 * MVP: hardcoded profiles for top assets.
 * Future: pull from CoinGecko/DeFiLlama/TokenUnlocks APIs.
 */

import type { ProjectProfile } from '../types/project-intelligence.types.js';

export const KNOWN_PROFILES: Record<string, Partial<ProjectProfile>> = {
  BTC: {
    name: 'Bitcoin',
    sector: 'l1',
    totalSupply: 21000000,
    circulatingSupply: 19800000,
    maxSupply: 21000000,
    launchType: 'fair_launch',
    teamReputation: 'STRONG',
    initialFloat: 1.0,
    insiderAllocation: 0.0,
    dailyActiveUsers: 800000,
    narrative: 'store-of-value',
  },
  ETH: {
    name: 'Ethereum',
    sector: 'l1',
    totalSupply: 120500000,
    circulatingSupply: 120500000,
    launchType: 'ico',
    teamReputation: 'STRONG',
    topFundsInvolved: ['Ethereum Foundation'],
    initialFloat: 0.80,
    insiderAllocation: 0.15,
    dailyActiveUsers: 500000,
    tvl: 50e9,
    revenue30d: 100e6,
    narrative: 'smart-contracts',
  },
  SOL: {
    name: 'Solana',
    sector: 'l1',
    totalSupply: 590000000,
    circulatingSupply: 440000000,
    launchType: 'vc_backed',
    teamReputation: 'STRONG',
    topFundsInvolved: ['a16z', 'Multicoin', 'Polychain', 'Jump Crypto'],
    totalFundingUsd: 335e6,
    initialFloat: 0.30,
    insiderAllocation: 0.48,
    dailyActiveUsers: 1500000,
    tvl: 8e9,
    revenue30d: 30e6,
    narrative: 'high-performance-l1',
  },
  XRP: {
    name: 'Ripple',
    sector: 'infra',
    totalSupply: 100000000000,
    circulatingSupply: 57000000000,
    maxSupply: 100000000000,
    launchType: 'ico',
    teamReputation: 'MID',
    insiderAllocation: 0.55,
    narrative: 'payments',
  },
  DOGE: {
    name: 'Dogecoin',
    sector: 'meme',
    totalSupply: 147000000000,
    circulatingSupply: 147000000000,
    launchType: 'fair_launch',
    teamReputation: 'WEAK',
    insiderAllocation: 0.0,
    narrative: 'meme',
  },
  ADA: {
    name: 'Cardano',
    sector: 'l1',
    totalSupply: 45000000000,
    circulatingSupply: 36000000000,
    maxSupply: 45000000000,
    launchType: 'ico',
    teamReputation: 'MID',
    insiderAllocation: 0.20,
    dailyActiveUsers: 50000,
    tvl: 500e6,
    narrative: 'research-driven-l1',
  },
  AVAX: {
    name: 'Avalanche',
    sector: 'l1',
    totalSupply: 720000000,
    circulatingSupply: 410000000,
    maxSupply: 720000000,
    launchType: 'vc_backed',
    teamReputation: 'STRONG',
    topFundsInvolved: ['a16z', 'Polychain', 'Galaxy Digital'],
    totalFundingUsd: 290e6,
    insiderAllocation: 0.42,
    tvl: 1.5e9,
    revenue30d: 5e6,
    narrative: 'subnets',
  },
  LINK: {
    name: 'Chainlink',
    sector: 'infra',
    totalSupply: 1000000000,
    circulatingSupply: 630000000,
    maxSupply: 1000000000,
    launchType: 'ico',
    teamReputation: 'STRONG',
    insiderAllocation: 0.35,
    dailyActiveUsers: 200000,
    narrative: 'oracles',
  },
  UNI: {
    name: 'Uniswap',
    sector: 'defi',
    totalSupply: 1000000000,
    circulatingSupply: 600000000,
    maxSupply: 1000000000,
    launchType: 'airdrop',
    teamReputation: 'STRONG',
    topFundsInvolved: ['a16z', 'Paradigm'],
    insiderAllocation: 0.40,
    dailyActiveUsers: 100000,
    tvl: 5e9,
    revenue30d: 50e6,
    narrative: 'dex',
  },
  AAVE: {
    name: 'Aave',
    sector: 'defi',
    totalSupply: 16000000,
    circulatingSupply: 15000000,
    maxSupply: 16000000,
    launchType: 'ico',
    teamReputation: 'STRONG',
    topFundsInvolved: ['Framework Ventures', 'Variant', 'Blockchain Capital'],
    insiderAllocation: 0.25,
    tvl: 15e9,
    revenue30d: 30e6,
    narrative: 'lending',
  },
  ARB: {
    name: 'Arbitrum',
    sector: 'l2',
    totalSupply: 10000000000,
    circulatingSupply: 3500000000,
    launchType: 'airdrop',
    teamReputation: 'STRONG',
    topFundsInvolved: ['Pantera', 'Haun Ventures'],
    totalFundingUsd: 120e6,
    insiderAllocation: 0.44,
    dailyActiveUsers: 200000,
    tvl: 3e9,
    revenue30d: 8e6,
    narrative: 'l2-scaling',
  },
  OP: {
    name: 'Optimism',
    sector: 'l2',
    totalSupply: 4294967296,
    circulatingSupply: 1300000000,
    launchType: 'airdrop',
    teamReputation: 'STRONG',
    topFundsInvolved: ['a16z', 'Paradigm'],
    totalFundingUsd: 178e6,
    insiderAllocation: 0.36,
    tvl: 800e6,
    revenue30d: 3e6,
    narrative: 'superchain',
  },
  SUI: {
    name: 'Sui',
    sector: 'l1',
    totalSupply: 10000000000,
    circulatingSupply: 3200000000,
    maxSupply: 10000000000,
    launchType: 'vc_backed',
    teamReputation: 'STRONG',
    topFundsInvolved: ['a16z', 'Jump Crypto', 'Electric Capital'],
    totalFundingUsd: 336e6,
    insiderAllocation: 0.50,
    dailyActiveUsers: 500000,
    tvl: 1.5e9,
    narrative: 'move-vm',
  },
  APT: {
    name: 'Aptos',
    sector: 'l1',
    totalSupply: 1100000000,
    circulatingSupply: 500000000,
    launchType: 'vc_backed',
    teamReputation: 'MID',
    topFundsInvolved: ['a16z', 'Multicoin', 'Binance Labs', 'FTX Ventures'],
    totalFundingUsd: 350e6,
    insiderAllocation: 0.51,
    tvl: 700e6,
    narrative: 'move-vm',
  },
  HYPE: {
    name: 'Hyperliquid',
    sector: 'defi',
    totalSupply: 1000000000,
    circulatingSupply: 333000000,
    launchType: 'airdrop',
    teamReputation: 'STRONG',
    topFundsInvolved: [],
    totalFundingUsd: 0,
    insiderAllocation: 0.30,
    dailyActiveUsers: 200000,
    revenue30d: 40e6,
    narrative: 'perp-dex',
  },
  PEPE: {
    name: 'Pepe',
    sector: 'meme',
    totalSupply: 420690000000000,
    circulatingSupply: 420690000000000,
    maxSupply: 420690000000000,
    launchType: 'fair_launch',
    teamReputation: 'WEAK',
    insiderAllocation: 0.0,
    narrative: 'meme',
  },
  INJ: {
    name: 'Injective',
    sector: 'l1',
    totalSupply: 100000000,
    circulatingSupply: 97000000,
    launchType: 'vc_backed',
    teamReputation: 'MID',
    topFundsInvolved: ['Binance Labs', 'Pantera'],
    totalFundingUsd: 40e6,
    insiderAllocation: 0.36,
    tvl: 50e6,
    narrative: 'cosmos-defi',
  },
  TIA: {
    name: 'Celestia',
    sector: 'infra',
    totalSupply: 1000000000,
    circulatingSupply: 250000000,
    launchType: 'vc_backed',
    teamReputation: 'STRONG',
    topFundsInvolved: ['Polychain', 'Placeholder', 'Galaxy Digital', 'Delphi Ventures'],
    totalFundingUsd: 55e6,
    insiderAllocation: 0.60,
    nextUnlockDate: '2026-10-31',
    nextUnlockPercent: 8,
    vestingEndDate: '2027-10-31',
    initialFloat: 0.15,
    narrative: 'modular',
  },
  WLD: {
    name: 'Worldcoin',
    sector: 'ai',
    totalSupply: 10000000000,
    circulatingSupply: 500000000,
    launchType: 'vc_backed',
    teamReputation: 'MID',
    topFundsInvolved: ['a16z', 'Khosla Ventures'],
    totalFundingUsd: 250e6,
    insiderAllocation: 0.25,
    initialFloat: 0.05,
    narrative: 'identity-ai',
  },
};

/**
 * Get project profile, merging known data with dynamic price data.
 */
export function getProjectProfile(
  asset: string,
  dynamicData?: Partial<ProjectProfile>,
): ProjectProfile {
  const known = KNOWN_PROFILES[asset.toUpperCase()] || {};
  const merged: ProjectProfile = {
    asset: asset.toUpperCase(),
    name: known.name || asset.toUpperCase(),
    totalSupply: 0,
    circulatingSupply: 0,
    currentPrice: 0,
    fdv: 0,
    marketCap: 0,
    ...known,
    ...dynamicData,
  };

  // Auto-compute FDV if not provided
  if (merged.fdv <= 0 && merged.currentPrice > 0 && merged.totalSupply > 0) {
    merged.fdv = merged.currentPrice * merged.totalSupply;
  }

  // Auto-compute market cap if not provided
  if (merged.marketCap <= 0 && merged.currentPrice > 0 && merged.circulatingSupply > 0) {
    merged.marketCap = merged.currentPrice * merged.circulatingSupply;
  }

  return merged;
}
