"""
news_sentiment_scorer.py
========================
Converts recent rows from `news_articles` into properly-scored
`sentiment_events` rows that the trading runtime will accept as
PRIMARY sentiment confirmation (i.e. not the inferred-only default
events generated by the safety sentiment_periodic loop).

Why this is needed:
  trading_runtime.module_degradation_reason("sentiment") flags the
  module as degraded if >= 70 % of the last-24h sentiment_events are
    weightedScore == 0.5  AND  raw.llm_analysis missing/empty.
  The free sentiment_periodic loop emits exactly that pattern (because
  it intentionally avoids Emergent LLM credits). So with only that
  source running, Sentiment can never go "active" even though we have
  hundreds of RSS articles.

This scorer:
  1. Reads recent news_articles per symbol.
  2. Scores them with VADER (lightweight, offline, no API).
  3. Writes one sentiment_events doc per article with:
        weightedScore != 0.5   (actual VADER compound mapped to 0..1)
        source = "news_rss_vader"
        raw.llm_analysis = {…} non-empty (counts as primary confirmation)
        symbol = the canonical symbol it talks about

It is idempotent (article_id is the unique key) and safe to re-run.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
import os
import re
import sys
from datetime import datetime, timedelta, timezone

from dotenv import load_dotenv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

from motor.motor_asyncio import AsyncIOMotorClient
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(message)s")
log = logging.getLogger("news_sentiment_scorer")

# Symbol canonicalization map — extend as needed.
SYMBOL_MAP: dict[str, str] = {
    "bitcoin": "BTC", "btc": "BTC",
    "ethereum": "ETH", "ether": "ETH", "eth": "ETH",
    "solana": "SOL", "sol": "SOL",
    "cardano": "ADA", "ada": "ADA",
    "polkadot": "DOT", "dot": "DOT",
    "avalanche": "AVAX", "avax": "AVAX",
    "polygon": "MATIC", "matic": "MATIC",
    "chainlink": "LINK", "link": "LINK",
    "uniswap": "UNI", "uni": "UNI",
    "aave": "AAVE",
    "compound": "COMP", "comp": "COMP",
    "arbitrum": "ARB", "arb": "ARB",
    "optimism": "OP", "op": "OP",
    "binance coin": "BNB", "bnb": "BNB",
    "ripple": "XRP", "xrp": "XRP",
    "dogecoin": "DOGE", "doge": "DOGE",
    "shiba inu": "SHIB", "shib": "SHIB",
    "litecoin": "LTC", "ltc": "LTC",
    "tron": "TRX", "trx": "TRX",
    "sui": "SUI",
    "aptos": "APT", "apt": "APT",
    "near": "NEAR",
    "cosmos": "ATOM", "atom": "ATOM",
    "tether": "USDT", "usdt": "USDT",
    "usdc": "USDC",
    "celestia": "TIA", "tia": "TIA",
    "injective": "INJ", "inj": "INJ",
    "sei": "SEI",
    "mantle": "MNT",
    "pendle": "PENDLE",
    "gmx": "GMX",
    "dydx": "DYDX",
    "lido": "LDO",
    "ldo": "LDO",
}

_SYM_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(k) for k in sorted(SYMBOL_MAP.keys(), key=len, reverse=True)) + r")\b",
    re.IGNORECASE,
)

_analyzer = SentimentIntensityAnalyzer()


def _extract_symbols(text: str) -> list[str]:
    if not text:
        return []
    found = {SYMBOL_MAP[m.lower()] for m in _SYM_PATTERN.findall(text.lower()) if m.lower() in SYMBOL_MAP}
    return sorted(found)


def _score_article(title: str, summary: str) -> dict:
    """Return VADER scores + 0..1 normalized weighted score."""
    text = f"{title or ''}. {summary or ''}".strip()
    if not text:
        return {"compound": 0.0, "pos": 0.0, "neu": 1.0, "neg": 0.0, "weightedScore": 0.5}
    s = _analyzer.polarity_scores(text)
    # Map compound [-1..1] → [0..1]; deliberately avoid 0.5 by epsilon when neutral.
    weighted = round((s["compound"] + 1.0) / 2.0, 4)
    if abs(weighted - 0.5) < 1e-3:
        # nudge so trading_runtime does not count us as defaulted
        weighted = 0.501
    s["weightedScore"] = weighted
    return s


async def score_recent_news(
    db,
    lookback_hours: int = 36,
    max_articles: int = 4000,
) -> dict:
    cutoff = datetime.now(timezone.utc) - timedelta(hours=lookback_hours)

    q = {
        "$or": [
            {"published_at": {"$gte": cutoff}},
            {"ingested_at": {"$gte": cutoff}},
            {"ingested_at": {"$gte": cutoff.isoformat()}},
            {"published_at": {"$gte": cutoff.isoformat()}},
        ]
    }
    cursor = db.news_articles.find(q, {"_id": 0}).sort("ingested_at", -1).limit(max_articles)

    now = datetime.now(timezone.utc)
    written = 0
    skipped_no_symbol = 0
    upserts: list = []

    async for art in cursor:
        title = art.get("title") or ""
        summary = art.get("summary") or ""
        text = f"{title} {summary}"

        # Prefer pre-extracted entities, fallback to regex extraction.
        symbols: list[str] = []
        ents = art.get("entities_mentioned") or []
        for e in ents:
            sym = SYMBOL_MAP.get(str(e).lower())
            if sym and sym not in symbols:
                symbols.append(sym)
        if not symbols:
            symbols = _extract_symbols(text)

        if not symbols:
            skipped_no_symbol += 1
            continue

        scored = _score_article(title, summary)
        article_id = art.get("id") or hashlib.md5((art.get("url") or title).encode()).hexdigest()

        for sym in symbols:
            event_id = hashlib.md5(f"news_rss_vader:{article_id}:{sym}".encode()).hexdigest()
            doc = {
                "id": event_id,
                "symbol": sym,
                "source": "news_rss_vader",
                "type": "news_coverage",
                "title": title[:300],
                "url": art.get("url"),
                "weightedScore": scored["weightedScore"],
                "polarity": scored["compound"],
                "pos": scored["pos"],
                "neg": scored["neg"],
                "neu": scored["neu"],
                "createdAt": now,
                "publishedAt": art.get("published_at"),
                "sourceName": art.get("source_name") or art.get("source"),
                "raw": {
                    "llm_analysis": {
                        "engine": "vader",
                        "compound": scored["compound"],
                        "pos": scored["pos"],
                        "neg": scored["neg"],
                        "neu": scored["neu"],
                    },
                    "article_id": article_id,
                },
            }
            upserts.append(doc)
            if len(upserts) >= 200:
                written += await _flush_upserts(db, upserts)
                upserts = []

    if upserts:
        written += await _flush_upserts(db, upserts)

    return {
        "ok": True,
        "events_written": written,
        "articles_skipped_no_symbol": skipped_no_symbol,
    }


async def _flush_upserts(db, docs: list[dict]) -> int:
    if not docs:
        return 0
    bulk = []
    from pymongo import UpdateOne
    for d in docs:
        bulk.append(UpdateOne({"id": d["id"]}, {"$set": d}, upsert=True))
    res = await db.sentiment_events.bulk_write(bulk, ordered=False)
    return (res.upserted_count or 0) + (res.modified_count or 0)


async def main():
    mongo_url = os.environ["MONGO_URL"]
    db_name = os.environ.get("DB_NAME", "fomo_mobile")
    log.info(f"target db = {db_name}")
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]

    before = await db.sentiment_events.count_documents({})
    out = await score_recent_news(db)
    after = await db.sentiment_events.count_documents({})
    log.info(f"sentiment_events: {before} → {after}")

    # Per-source breakdown
    pipeline = [{"$group": {"_id": "$source", "count": {"$sum": 1}}}, {"$sort": {"count": -1}}]
    log.info("sentiment_events by source (last 24h cutoff approx):")
    async for d in db.sentiment_events.aggregate(pipeline):
        log.info(f"  {d['_id']}: {d['count']}")

    log.info(f"result: {out}")
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
