"""
Signal Engine Alerts API Tests
==============================
Tests for entity_alerts endpoints generated by Signal Engine:
- GET /api/intel/admin/alerts (list with filters)
- GET /api/intel/admin/alerts/triggered (triggered only)
- GET /api/intel/admin/alerts/summary (dashboard summary)

Signal Engine formula:
  signalScore = velocity*0.35 + sentiment*0.25 + importance*0.20 + volume*0.10 + trend*0.10

Signal types: MOMENTUM, RISK, BREAKOUT, NOISE, ATTENTION, NEUTRAL
Trigger: signalScore > 70 && confidence > 60 && importanceBand != LOW
Dedupe: entityId + signalType + hourBucket
"""

import pytest
import requests
import os

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")


class TestAlertsListEndpoint:
    """Test GET /api/intel/admin/alerts endpoint"""

    def test_alerts_returns_200(self):
        """Alerts endpoint returns 200 OK"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        print("PASS: /api/intel/admin/alerts returns 200")

    def test_alerts_has_total_count(self):
        """Alerts response has total count"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        assert "total" in data, "Response missing 'total' field"
        assert isinstance(data["total"], int), "total should be integer"
        assert data["total"] > 0, f"Expected alerts > 0, got {data['total']}"
        print(f"PASS: total alerts = {data['total']}")

    def test_alerts_has_triggered_count(self):
        """Alerts response has triggered count"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        assert "triggered" in data, "Response missing 'triggered' field"
        assert isinstance(data["triggered"], int), "triggered should be integer"
        print(f"PASS: triggered alerts = {data['triggered']}")

    def test_alerts_has_types_breakdown(self):
        """Alerts response has types breakdown"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        assert "types" in data, "Response missing 'types' field"
        assert isinstance(data["types"], dict), "types should be dict"
        # Check for expected signal types
        valid_types = {"MOMENTUM", "RISK", "BREAKOUT", "NOISE", "ATTENTION", "NEUTRAL"}
        for signal_type in data["types"].keys():
            assert signal_type in valid_types, f"Unknown signal type: {signal_type}"
        print(f"PASS: types breakdown = {data['types']}")

    def test_alerts_has_alerts_list(self):
        """Alerts response has alerts list"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        assert "alerts" in data, "Response missing 'alerts' field"
        assert isinstance(data["alerts"], list), "alerts should be list"
        assert len(data["alerts"]) > 0, "Expected at least one alert"
        print(f"PASS: alerts list has {len(data['alerts'])} items")


class TestAlertsFiltering:
    """Test alerts filtering parameters"""

    def test_triggered_only_filter(self):
        """Filter triggered_only=true returns only triggered alerts"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?triggered_only=true")
        assert response.status_code == 200
        data = response.json()
        
        # All returned alerts should be triggered
        for alert in data["alerts"]:
            assert alert.get("triggered") == True, f"Alert {alert.get('entityId')} not triggered"
        
        print(f"PASS: triggered_only filter works, {len(data['alerts'])} triggered alerts")

    def test_signal_type_momentum_filter(self):
        """Filter signal_type=MOMENTUM returns only momentum alerts"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?signal_type=MOMENTUM")
        assert response.status_code == 200
        data = response.json()
        
        # All returned alerts should be MOMENTUM type
        for alert in data["alerts"]:
            assert alert.get("signalType") == "MOMENTUM", f"Alert has type {alert.get('signalType')}, expected MOMENTUM"
        
        print(f"PASS: signal_type=MOMENTUM filter works, {len(data['alerts'])} momentum alerts")

    def test_signal_type_risk_filter(self):
        """Filter signal_type=RISK returns only risk alerts"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?signal_type=RISK")
        assert response.status_code == 200
        data = response.json()
        
        # All returned alerts should be RISK type
        for alert in data["alerts"]:
            assert alert.get("signalType") == "RISK", f"Alert has type {alert.get('signalType')}, expected RISK"
        
        print(f"PASS: signal_type=RISK filter works, {len(data['alerts'])} risk alerts")

    def test_importance_band_filter(self):
        """Filter importance_band=HIGH returns only high importance alerts"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?importance_band=HIGH")
        assert response.status_code == 200
        data = response.json()
        
        # All returned alerts should be HIGH importance
        for alert in data["alerts"]:
            assert alert.get("importanceBand") == "HIGH", f"Alert has band {alert.get('importanceBand')}, expected HIGH"
        
        print(f"PASS: importance_band=HIGH filter works, {len(data['alerts'])} high importance alerts")


class TestTriggeredAlertsEndpoint:
    """Test GET /api/intel/admin/alerts/triggered endpoint"""

    def test_triggered_returns_200(self):
        """Triggered alerts endpoint returns 200 OK"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        print("PASS: /api/intel/admin/alerts/triggered returns 200")

    def test_triggered_has_count(self):
        """Triggered response has count"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        assert "count" in data, "Response missing 'count' field"
        assert isinstance(data["count"], int), "count should be integer"
        print(f"PASS: triggered count = {data['count']}")

    def test_triggered_has_alerts_list(self):
        """Triggered response has alerts list"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        assert "alerts" in data, "Response missing 'alerts' field"
        assert isinstance(data["alerts"], list), "alerts should be list"
        print(f"PASS: triggered alerts list has {len(data['alerts'])} items")

    def test_triggered_sorted_by_signal_score(self):
        """Triggered alerts are sorted by signalScore descending"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        alerts = data["alerts"]
        
        if len(alerts) >= 2:
            scores = [a.get("signalScore", 0) for a in alerts]
            for i in range(len(scores) - 1):
                assert scores[i] >= scores[i+1], f"Not sorted: {scores[i]} < {scores[i+1]}"
        
        print(f"PASS: triggered alerts sorted by signalScore (top: {alerts[0].get('signalScore') if alerts else 'N/A'})")

    def test_all_triggered_alerts_meet_criteria(self):
        """All triggered alerts meet trigger criteria: signalScore > 70 && confidence > 60 && importanceBand != LOW"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        
        for alert in data["alerts"]:
            signal_score = alert.get("signalScore", 0)
            confidence = alert.get("confidence", 0)
            importance_band = alert.get("importanceBand", "LOW")
            
            assert signal_score > 70, f"Alert {alert.get('entityId')} has signalScore {signal_score} <= 70"
            assert confidence > 60, f"Alert {alert.get('entityId')} has confidence {confidence} <= 60"
            assert importance_band != "LOW", f"Alert {alert.get('entityId')} has importanceBand LOW"
        
        print(f"PASS: all {len(data['alerts'])} triggered alerts meet criteria")


class TestAlertsSummaryEndpoint:
    """Test GET /api/intel/admin/alerts/summary endpoint"""

    def test_summary_returns_200(self):
        """Summary endpoint returns 200 OK"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        print("PASS: /api/intel/admin/alerts/summary returns 200")

    def test_summary_has_total_alerts(self):
        """Summary has total_alerts count"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "total_alerts" in data, "Response missing 'total_alerts' field"
        assert isinstance(data["total_alerts"], int), "total_alerts should be integer"
        print(f"PASS: total_alerts = {data['total_alerts']}")

    def test_summary_has_triggered_count(self):
        """Summary has triggered_count"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "triggered_count" in data, "Response missing 'triggered_count' field"
        assert isinstance(data["triggered_count"], int), "triggered_count should be integer"
        print(f"PASS: triggered_count = {data['triggered_count']}")

    def test_summary_has_type_distribution(self):
        """Summary has type_distribution"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "type_distribution" in data, "Response missing 'type_distribution' field"
        assert isinstance(data["type_distribution"], dict), "type_distribution should be dict"
        
        # Each type should have count and avgScore
        for signal_type, info in data["type_distribution"].items():
            assert "count" in info, f"type_distribution[{signal_type}] missing 'count'"
            assert "avgScore" in info, f"type_distribution[{signal_type}] missing 'avgScore'"
        
        print(f"PASS: type_distribution = {data['type_distribution']}")

    def test_summary_has_importance_bands(self):
        """Summary has importance_bands"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "importance_bands" in data, "Response missing 'importance_bands' field"
        assert isinstance(data["importance_bands"], dict), "importance_bands should be dict"
        
        # Each band should have count and triggered
        for band, info in data["importance_bands"].items():
            assert "count" in info, f"importance_bands[{band}] missing 'count'"
            assert "triggered" in info, f"importance_bands[{band}] missing 'triggered'"
        
        print(f"PASS: importance_bands = {data['importance_bands']}")

    def test_summary_has_top_momentum(self):
        """Summary has top_momentum list"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "top_momentum" in data, "Response missing 'top_momentum' field"
        assert isinstance(data["top_momentum"], list), "top_momentum should be list"
        print(f"PASS: top_momentum has {len(data['top_momentum'])} items")

    def test_summary_has_top_risk(self):
        """Summary has top_risk list"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        data = response.json()
        assert "top_risk" in data, "Response missing 'top_risk' field"
        assert isinstance(data["top_risk"], list), "top_risk should be list"
        print(f"PASS: top_risk has {len(data['top_risk'])} items")


class TestAlertSchema:
    """Test entity_alerts document schema"""

    def test_alert_has_required_fields(self):
        """Each alert has all required fields"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=10")
        data = response.json()
        
        required_fields = [
            "entityId", "signalScore", "signalType", "confidence", 
            "triggered", "velocity", "volume", "importance", "importanceBand"
        ]
        
        for alert in data["alerts"]:
            for field in required_fields:
                assert field in alert, f"Alert missing required field: {field}"
        
        print(f"PASS: all alerts have required fields: {required_fields}")

    def test_alert_velocity_structure(self):
        """Alert velocity field has correct structure"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=5")
        data = response.json()
        
        for alert in data["alerts"]:
            velocity = alert.get("velocity", {})
            assert "twitter" in velocity, "velocity missing 'twitter'"
            assert "news" in velocity, "velocity missing 'news'"
            assert "score" in velocity, "velocity missing 'score'"
        
        print("PASS: velocity structure correct (twitter, news, score)")

    def test_alert_volume_structure(self):
        """Alert volume field has correct structure"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=5")
        data = response.json()
        
        for alert in data["alerts"]:
            volume = alert.get("volume", {})
            assert "mentionCount24h" in volume, "volume missing 'mentionCount24h'"
            assert "newsCount24h" in volume, "volume missing 'newsCount24h'"
            assert "twitterCount24h" in volume, "volume missing 'twitterCount24h'"
            assert "score" in volume, "volume missing 'score'"
        
        print("PASS: volume structure correct (mentionCount24h, newsCount24h, twitterCount24h, score)")

    def test_alert_has_future_return_fields(self):
        """Triggered alerts have futureReturn24h and futureReturn7d fields (null for now)"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        
        for alert in data["alerts"]:
            # These fields should exist (even if null)
            assert "futureReturn24h" in alert or alert.get("futureReturn24h") is None, "Missing futureReturn24h"
            assert "futureReturn7d" in alert or alert.get("futureReturn7d") is None, "Missing futureReturn7d"
        
        print("PASS: triggered alerts have futureReturn24h and futureReturn7d fields")

    def test_signal_score_range(self):
        """Signal scores are in valid range 0-100"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=50")
        data = response.json()
        
        for alert in data["alerts"]:
            score = alert.get("signalScore", 0)
            assert 0 <= score <= 100, f"signalScore {score} out of range [0, 100]"
        
        print("PASS: all signalScores in valid range [0, 100]")

    def test_confidence_range(self):
        """Confidence scores are in valid range 0-100"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=50")
        data = response.json()
        
        for alert in data["alerts"]:
            conf = alert.get("confidence", 0)
            assert 0 <= conf <= 100, f"confidence {conf} out of range [0, 100]"
        
        print("PASS: all confidence scores in valid range [0, 100]")


class TestSignalTypesDistribution:
    """Test signal types distribution matches expected values"""

    def test_signal_types_present(self):
        """All expected signal types are present"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        
        types = data.get("types", {})
        # At minimum, NEUTRAL should be present (most common)
        assert len(types) > 0, "No signal types found"
        print(f"PASS: signal types present: {list(types.keys())}")

    def test_neutral_is_most_common(self):
        """NEUTRAL type should be most common (based on classification logic)"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        data = response.json()
        
        types = data.get("types", {})
        if "NEUTRAL" in types:
            neutral_count = types["NEUTRAL"]
            # NEUTRAL should be significant portion
            total = sum(types.values())
            neutral_pct = (neutral_count / total) * 100 if total > 0 else 0
            print(f"PASS: NEUTRAL = {neutral_count} ({neutral_pct:.1f}% of total)")
        else:
            print("INFO: No NEUTRAL alerts found")


class TestTopTriggeredAlerts:
    """Test top triggered alerts data"""

    def test_top_triggered_entities(self):
        """Verify top triggered alerts have high scores"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        data = response.json()
        
        if data["alerts"]:
            top_3 = data["alerts"][:3]
            print("Top 3 triggered alerts:")
            for alert in top_3:
                entity = alert.get("entityId", "unknown")
                score = alert.get("signalScore", 0)
                signal_type = alert.get("signalType", "unknown")
                confidence = alert.get("confidence", 0)
                print(f"  - {entity}: score={score}, type={signal_type}, confidence={confidence}")
            
            # Top alert should have high score
            assert top_3[0].get("signalScore", 0) >= 70, "Top alert score should be >= 70"
        
        print("PASS: top triggered alerts verified")


class TestDedupeLogic:
    """Test dedupe mechanism (same entity+type+hour should not duplicate)"""

    def test_no_duplicate_dedupe_keys(self):
        """No duplicate dedupeKey values in alerts"""
        response = requests.get(f"{BASE_URL}/api/intel/admin/alerts?limit=200")
        data = response.json()
        
        # Note: dedupeKey is excluded from response, but we can check entityId+signalType+hourBucket
        # Since hourBucket is also excluded, we check for entity+type uniqueness in current batch
        seen = set()
        for alert in data["alerts"]:
            entity_id = alert.get("entityId", "")
            signal_type = alert.get("signalType", "")
            hour_bucket = alert.get("hourBucket", "")
            
            if hour_bucket:  # If hourBucket is present
                key = f"{entity_id}:{signal_type}:{hour_bucket}"
                assert key not in seen, f"Duplicate dedupe key found: {key}"
                seen.add(key)
        
        print(f"PASS: no duplicate dedupe keys in {len(data['alerts'])} alerts")


class TestDataIntegrity:
    """Test data integrity between endpoints"""

    def test_triggered_count_consistency(self):
        """Triggered count is consistent between endpoints"""
        # Get from /alerts
        alerts_resp = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        alerts_data = alerts_resp.json()
        triggered_from_alerts = alerts_data.get("triggered", 0)
        
        # Get from /alerts/triggered
        triggered_resp = requests.get(f"{BASE_URL}/api/intel/admin/alerts/triggered")
        triggered_data = triggered_resp.json()
        triggered_from_endpoint = triggered_data.get("count", 0)
        
        # Get from /alerts/summary
        summary_resp = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        summary_data = summary_resp.json()
        triggered_from_summary = summary_data.get("triggered_count", 0)
        
        # All should match
        assert triggered_from_alerts == triggered_from_endpoint, \
            f"Mismatch: /alerts.triggered={triggered_from_alerts} vs /alerts/triggered.count={triggered_from_endpoint}"
        assert triggered_from_alerts == triggered_from_summary, \
            f"Mismatch: /alerts.triggered={triggered_from_alerts} vs /alerts/summary.triggered_count={triggered_from_summary}"
        
        print(f"PASS: triggered count consistent across endpoints: {triggered_from_alerts}")

    def test_total_count_consistency(self):
        """Total count is consistent between endpoints"""
        # Get from /alerts
        alerts_resp = requests.get(f"{BASE_URL}/api/intel/admin/alerts")
        alerts_data = alerts_resp.json()
        total_from_alerts = alerts_data.get("total", 0)
        
        # Get from /alerts/summary
        summary_resp = requests.get(f"{BASE_URL}/api/intel/admin/alerts/summary")
        summary_data = summary_resp.json()
        total_from_summary = summary_data.get("total_alerts", 0)
        
        assert total_from_alerts == total_from_summary, \
            f"Mismatch: /alerts.total={total_from_alerts} vs /alerts/summary.total_alerts={total_from_summary}"
        
        print(f"PASS: total count consistent across endpoints: {total_from_alerts}")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
